# Generated by Django 4.1.5 on 2023-01-11 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationgroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='notificationgroup',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
