# Generated by Django 4.1.5 on 2023-01-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimelog',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
