# Generated by Django 4.1.5 on 2023-01-09 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_website_name_alter_website_auth_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimelog',
            name='downtime_duration',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='downtimelog',
            name='http_status',
            field=models.PositiveSmallIntegerField(default=404),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downtimelog',
            name='response_time',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
