# Generated by Django 4.1.5 on 2023-01-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_downtimelog_downtime_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downtimelog',
            old_name='down_time',
            new_name='downtime_end',
        ),
        migrations.RenameField(
            model_name='downtimelog',
            old_name='up_time',
            new_name='downtime_start',
        ),
    ]
