# Generated by Django 4.1.5 on 2023-01-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_rename_down_time_downtimelog_downtime_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimelog',
            name='downtime_duration',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
