# Generated by Django 4.1.5 on 2023-01-09 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_downtimelog_downtime_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='time_added',
            new_name='created_time',
        ),
    ]
