# Generated by Django 4.1.5 on 2023-01-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_rename_time_added_website_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimelog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimelog', to='monitoring.website'),
        ),
    ]
