# Generated by Django 4.1.5 on 2023-01-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_downtimelog_http_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=60)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.website')),
            ],
        ),
    ]
