# Generated by Django 4.1.5 on 2023-01-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_monitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='alias',
            new_name='name',
        ),
    ]
