# Generated by Django 4.1.5 on 2023-01-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apikey_delete_downtimelog_delete_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
